org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.enableNativeCompilerSettings=true
storePassword=android
keyPassword=android
keyAlias=upload
storeFile=upload-keystore.jks
android.enable16KbPageSizes=true
android.experimental.enable16kPageSize=true
android.bundle.enableUncompressedNativeLibs=true