org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.enableNativeCompilerSettings=true
storePassword=android
keyPassword=android
keyAlias=upload
storeFile=upload-keystore.jks
android.enable16KbPageSizes=true
android.experimental.enable16kPageSize=true
android.bundle.enableUncompressedNativeLibs=true
